In [53]:
import numpy as np

In [54]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [55]:
b = np.array([[8,3,2,5],[12,23,34,54]])
print(b)
b.shape

[[ 8  3  2  5]
 [12 23 34 54]]


(2, 4)

In [56]:
b[1,0]

np.int64(12)

In [57]:
b[1,2]=100
print(b)

[[  8   3   2   5]
 [ 12  23 100  54]]


In [58]:
b[:,2]=5
print(b)

[[ 8  3  5  5]
 [12 23  5 54]]


In [59]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

c[0,1,1]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


np.int64(4)

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
np.full((2,2),(99))

array([[99, 99],
       [99, 99]])

In [63]:
np.random.rand(4,5)

array([[0.42857062, 0.35531433, 0.2896802 , 0.82902412, 0.40111776],
       [0.83119917, 0.57411842, 0.41756329, 0.69053733, 0.09924545],
       [0.98793744, 0.04707444, 0.31939493, 0.88568845, 0.40066985],
       [0.53328436, 0.73127755, 0.53875292, 0.61855879, 0.76544271]])

In [69]:
f=np.array([4,5,6,7])
g=f.copy()
print(g)


[4 5 6 7]


In [70]:
g + 2

array([6, 7, 8, 9])

In [71]:
f + b

array([[12,  8, 11, 12],
       [16, 28, 11, 61]])

In [72]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [76]:
j=np.ones((2,3))
print(j)
k=np.full((3,2),4)
print (k)
np.matmul(j, k)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


array([[12., 12.],
       [12., 12.]])